# Generated by Django 3.2.4 on 2021-06-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_alter_host_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_pics', verbose_name='Site Picture'),
        ),
        migrations.AlterField(
            model_name='host',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
    ]
