# Generated by Django 3.2.4 on 2021-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_alter_host_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./site_pics/', verbose_name='Site Picture'),
        ),
    ]
