# Generated by Django 3.2.4 on 2021-06-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_alter_host_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='./site_pics/')),
                ('host', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='host.host')),
            ],
        ),
    ]
