# Generated by Django 3.2.4 on 2021-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_hostimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='host',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='./site_pics/', verbose_name='Site Picture'),
        ),
        migrations.AddField(
            model_name='host',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='./site_pics/', verbose_name='Site Picture'),
        ),
        migrations.DeleteModel(
            name='HostImage',
        ),
    ]
