# Generated by Django 3.2.4 on 2021-06-25 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_alter_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$', 'String must contain a zipcode.')], verbose_name='Zip Code'),
        ),
    ]
