# Generated by Django 3.2.4 on 2021-06-25 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_alter_host_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='zip_code',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$', 'Sorry, please enter a valid zip code.')], verbose_name='Zip Code'),
        ),
    ]
